### ISSUE TITLE
How to set DevicePolicyManager#isLockTaskPermitted to true?

### ISSUE THREAD

**Issue by blackbusters** [MewsSystems/mews-flutter#179]
Can you tell me how to enable this and directly launch locktask without user permission?

I've tried step by step guide to enable device owner using adb and set Receiver in AndroidManifest.xml like this :

        <receiver
            android:name="com.example.kiosk.AppAdminReceiver"
            android:label="kioskadmin"
            android:permission="android.permission.BIND_DEVICE_ADMIN">
            <meta-data
                android:name="android.app.device_admin"
                android:resource="@xml/device_admin_receiver" />
            <intent-filter>
                <action android:name="android.intent.action.DEVICE_ADMIN_ENABLED"/>
                <action android:name="android.intent.action.PROFILE_PROVISIONING_COMPLETE"/>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
            </intent-filter>
        </receiver>

Then i run this adb command :
`adb shell dpm set-device-owner com.example.kiosk/.AppAdminReceiver`

The adb resulted in success as shown below :
`Success: Device owner set to package ComponentInfo{com.example.kiosk/com.example.kiosk.AppAdminReceiver}
Active admin set to component {com.example.kiosk/com.example.kiosk.AppAdminReceiver}`

But when i tried to run my app again and run startKioskMode(), it shows screen pin hint and user can exit the screen pinning by pressing back and overview button.

Any help would greatly appreciated..

Thank you.

**Comment by ookami-kb** [comment]
Hi, 

In order to use lock task mode without the user being able to exit it, you need to explicitly allow it for the app. You can use something like this (assuming that the package name for your Kiosk app is `com.example.kiosk`):

```kotlin
val policyManager = context.getSystemService(Context.DEVICE_POLICY_SERVICE) as? DevicePolicyManager
        ?: throw ClassCastException("DevicePolicyManager is not available")
val adminComponent = ComponentName(context, AppAdminReceiver::class.java)

policyManager.setLockTaskPackages(adminComponent, arrayOf("com.example.kiosk"))
```

Keep in mind that this code needs to be run *after* you grant Device Owner permissions.

**Comment by blackbusters** [comment]
Hi...

Thanks for your help!! 
I've implemented your code in my MainActivity.kt and now start lock won't ask for user action anymore (as expected).

But i have one more problem here, user can still get out kiosk mode by pressing back and overview button.

In newer tablet, usually these buttons are soft key and they will disappear after start lock, but in my test gadget using Samsung Tab A6 (Android 5.0), it is still using hardware key, so it can be pressed by user.

Is there any way to disable this?

**Comment by ookami-kb** [comment]
Hm, that's weird. IIRC it shouldn't allow the user to exit Lock Task mode manually.

**Comment by blackbusters** [comment]
Well, i guess this shouldn't be a problem for using this package, and i'm still satisfied with this result.

I will close this for now, thanks !!
