### ISSUE TITLE
Huge increase in APK size with kiosk_mode 

### ISSUE THREAD

**Issue by gomcodoctor** [MewsSystems/mews-flutter#229]
On installing kiosk_mode, APK size increased from 15 MB to 25 MB !! , is it normal?

**Comment by ookami-kb** [comment]
@gomcodoctor there shouldn't be such a huge increase.

I've checked the example app – it's 34.9 MB with `kiosk_mode` vs 34.4 MB without it. If you can provide 2 apks you've got with and without the plugin, I can take a look.

**Comment by ookami-kb** [comment]
Can you probably share the stat of the apk from Android Studio? (File -> Profile or debug APK).

**Comment by gomcodoctor** [comment]
app.apk size is same as earlier.

size of app-arm64-v8a-release.apk is increased from 15 MB to 25 MB

![image](https://user-images.githubusercontent.com/10648299/181683352-a6bffe0d-b48f-4d35-a5c9-3325419e7ca1.png)

![image](https://user-images.githubusercontent.com/10648299/181683392-4de26681-4285-4bc3-9322-cdd74d7edf5a.png)

**Comment by ookami-kb** [comment]
Yeah, looks weird. But I'm afraid it's hard to tell anything specific without the apks.

**Comment by ookami-kb** [comment]
Actually, it can be related to this one: https://stackoverflow.com/questions/62440105/apk-size-increased-35mb-when-bumping-min-sdk-from-21-to-24

That would explain why the download size is 15.1 MB which is close to the previous size of the apk.

**Comment by gomcodoctor** [comment]
yes that could be the reason because I changed minSdkVersion to 23 recently, maybe installing this plugin was coincidence

**Comment by ookami-kb** [comment]
The plugin defines `minSdkVersion 23` as well. Ok, closing the issue.
