### ISSUE TITLE
Is it possible to set password for kiosk mode in Android?

### ISSUE THREAD

**Issue by leduchung** [MewsSystems/mews-flutter#232]
Dear devs,

It is about the kiosk_mode package. I want to programmatically set the password to lock the app, is it possible to implement it?

Many thanks,

**Comment by ookami-kb** [comment]
Hi, this library is just a proxy to the native methods. Do you have some native method in mind that provides this functionality?

**Comment by leduchung** [comment]
Hi thanks. I have no idea about a native methods, so I would like to know if it is possible but not implemented, or not possible at the moment. It seems not possible.
