### ISSUE TITLE
Android 12 app not going into kiosk mode 

### ISSUE THREAD

**Issue by arth17singh** [MewsSystems/mews-flutter#313]
In Android 9 kiosk mode is working fine but in Android 12 the app is pinned instead of going to kiosk mode. How can this issue be resolved?

**Comment by ookami-kb** [comment]
It doesn't depend on OS version, in order to force the app to stay in kiosk mode, your app should have the corresponding permission – see lock task mode vs screen pinning: https://developer.android.com/work/dpc/dedicated-devices/lock-task-mode
