### ISSUE TITLE
Notification panel is always displayed in kiosk mode

### ISSUE THREAD

**Issue by MarkAngheloDelapaz** [MewsSystems/mews-flutter#643]
Notification panel is always displayed in kiosk mode issue
The bug is always occurred using this step.
Steps:
Open the application that is pinned 
then pull down the notification panel/bar to display
and touch the notification panel, so the notification panel does not close anymore.

I just want to know if this is a common issue in kiosk mode or there is a possible fix. Thank you

**Comment by alboiuvlad29** [comment]
This looks to be a vendor-specific issue as it doesn't happen with the example app on stock android.
