### ISSUE TITLE
[Android] "Execution failed for task ':kiosk_mode:compileDebugKotlin'" ('compileDebugJavaWithJavac' (1.8))

### ISSUE THREAD

**Issue by Kuhlemann** [MewsSystems/mews-flutter#694]
Android Studio Ladybug (2024.2.1) seems to be shipped with Java 21.

Since I updated Android Studio to Ladybug I get the following error when compiling my Android version:
> Inconsistent JVM-target compatibility detected for tasks 'compileDebugJavaWithJavac' (1.8) and 'compileDebugKotlin' (21).

When I remove kiosk_mode from pubspec.yaml my build (with a lot of other pub.dev-packages) compiles without any problems.
So the problem only occurs within kiosk_mode.

android\app\build.grade:
```
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_21
    }
```

android\gradle\gradle-wrapper.properties:
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.10.2-all.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

android\settings.gradle:
```
plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "8.7.0" apply false
    id "org.jetbrains.kotlin.android" version "1.9.24" apply false
}
```

**Comment by alboiuvlad29** [comment]
Should be fixed by https://github.com/MewsSystems/mews-flutter/pull/695.
