### ISSUE TITLE
Remove warning or message from device when activate kiosk mode

### ISSUE THREAD

**Issue by iqbalme** [MewsSystems/mews-flutter#704]
Hi, I have tried this on 2 devices and it is working on both. But everytime I started to activate the kiosk mode, it shows message about how to unpin this app.

Can I just hide that message, so the users won't know about it?

![Screenshot_1732057388](https://github.com/user-attachments/assets/d054e7e8-36ea-4a0e-881d-3f53f34c22be)

**Comment by alboiuvlad29** [comment]
Hey, 

Looks like it's similar to https://github.com/MewsSystems/mews-flutter/issues/701.
As far as I know, not in this form. This message is provided by the android system. Different vendors could display different messages. The only way to disable this is through actually having a separate app acting as a [device policy controller](https://developer.android.com/work/dpc/build-dpc). You can read more about it in [android's official docs](https://developer.android.com/reference/android/app/admin/DevicePolicyManager.html#setLockTaskPackages(android.content.ComponentName,%20java.lang.String%5B%5D)).

**Comment by iqbalme** [comment]
Thank you for your answer
